import { CssBaseline } from "@mui/material";
import type { AppProps } from "next/app";
import Head from "next/head";

import "./treeHack.css";
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <CssBaseline />
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
