import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [blockNum, setBlockNum] = useState<number>();
  const [loading, setLoading] = useState(false);

  const onClick = async () => {
    setLoading(true);

    const test = await fetch("/api/blockNum");
    const data = await test.json();
    setBlockNum(data.blockNum);

    setLoading(false);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      <Head>
        <title>Nextjs App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ textAlign: "center", height: "100%" }}>
        <h1>Ethereum Block Number</h1>
        <h2>{loading ? "Loading..." : blockNum}</h2>
        <button onClick={onClick}>Get Current Block Number</button>
      </main>

      <footer>
        <a
          href="https://github.com/boilerblockchain/Technical-Intro-to-Blockchain/tree/main/0%20Start%20Here"
          target="_blank"
          rel="noopener noreferrer"
        >
          Github
        </a>
      </footer>
    </div>
  );
};

export default Home;
